export {
  calcHmoGrossMonthlyIncome,
  calcHmoMoneyNeededIn,
  calcHmoMonthlyOperatingCosts,
  calcHmoMonthlyProfit,
  calcSaMonthlyIncome,
  calcSaYearlyIncome,
  calcSaBreakEvenOccupancy,
  calcSaProfit,
  calcSaTotalCosts,
  calcMonthlyMortgageCost,
  calcManagementFee,
  calcDeposit,
  calcTotalCostToBuy,
  calcRoi,
  calcHmoYear1AnnualProfit,
  calcBillItemsTotal,
  calcHmoSummary,
  calcSaSummary,
  // Unit conversion helpers
  poundsToPence,
  penceToPounds,
  percentToDecimal,
  decimalToPercent,
} from './calculations';

export type {
  HmoRoomInput,
  UpfrontCostParams,
  HmoMonthlyOperatingCostParams,
  BuyCostParams,
  BillItemInput,
  SaTotalCostsParams,
  HmoSummaryInput,
  HmoSummaryResult,
  SaSummaryInput,
  SaSummaryResult,
} from './calculations';
